enableTelemetry: false

nodeLinker: node-modules

npmScopes:
  fortawesome:
    npmRegistryServer: 'https://npm.fontawesome.com'

packageExtensions:
  '@graphql-codegen/cli@*':
    peerDependenciesMeta:
      '@types/node':
        optional: true
      'ts-node':
        optional: true
      'typescript':
        optional: true
  '@graphql-tools/graphql-tag-pluck@*':
    peerDependenciesMeta:
      '@babel/core':
        optional: true
  '@storybook/manager-api@*':
    peerDependenciesMeta:
      react:
        optional: true
      react-dom:
        optional: true
  '@storybook/codemod@*':
    peerDependenciesMeta:
      '@babel/core':
        optional: true
      '@babel/preset-env':
        optional: true
  '@storybook/core-server@*':
    peerDependenciesMeta:
      react:
        optional: true
      react-dom:
        optional: true
  '@storybook/react-webpack5@*':
    peerDependenciesMeta:
      webpack:
        optional: true
  'graphql-config@*':
    peerDependenciesMeta:
      '@types/node':
        optional: true
      'typescript':
        optional: true
