enableGlobalCache: false
enableTelemetry: false

nodeLinker: node-modules

npmScopes:
  fortawesome:
    npmRegistryServer: 'https://npm.fontawesome.com'
packageExtensions:
  '@endemolshinegroup/cosmiconfig-typescript-loader@*':
    peerDependenciesMeta:
      typescript:
        optional: true

yarnPath: .yarn/releases/yarn-3.2.1.cjs
