enableTelemetry: false

nodeLinker: node-modules

npmScopes:
  fortawesome:
    npmRegistryServer: 'https://npm.fontawesome.com'

packageExtensions:
  '@graphql-codegen/cli@*':
    dependencies:
      '@types/node': '*'
      'ts-node': '*'
      'typescript': '*'
  '@graphql-tools/graphql-tag-pluck@*':
    dependencies:
      '@babel/core': '*'
  '@storybook/manager-api@*':
    peerDependenciesMeta:
      react:
        optional: true
      react-dom:
        optional: true
  '@storybook/codemod@*':
    dependencies:
      '@babel/core': '*'
      '@babel/preset-env': '*'
  '@storybook/core-server@*':
    peerDependenciesMeta:
      react:
        optional: true
      react-dom:
        optional: true
  '@storybook/react-webpack5@*':
    peerDependencies:
      webpack: ^5.0.0
  'graphql-config@*':
    dependencies:
      '@types/node': '*'
      'typescript': '*'
