enableTelemetry: false

nodeLinker: node-modules

npmScopes:
  fortawesome:
    npmRegistryServer: 'https://npm.fontawesome.com'

packageExtensions:
  '@cypress/code-coverage@*':
    dependencies:
      '@babel/core': '*'
      '@babel/preset-env': '*'
      'babel-loader': '*'
      'webpack': '*'
  '@graphql-tools/graphql-tag-pluck@*':
    peerDependenciesMeta:
      '@babel/core':
        optional: true
  '@whatwg-node/fetch@*':
    dependencies:
      '@types/node': '*'
