enableTelemetry: false

nodeLinker: node-modules

packageExtensions:
  '@cypress/code-coverage@*':
    dependencies:
      '@babel/core': '*'
      '@babel/preset-env': '*'
      'babel-loader': '*'
      'webpack': '*'
  '@graphql-tools/graphql-tag-pluck@*':
    peerDependenciesMeta:
      '@babel/core':
        optional: true
