enableTelemetry: false

nodeLinker: node-modules

npmScopes:
  fortawesome:
    npmRegistryServer: 'https://npm.fontawesome.com'

packageExtensions:
  '@storybook/addon-docs@*':
    dependencies:
      '@babel/core': ^7.0.0
      webpack: ^5.0.0
  '@storybook/addons@*':
    peerDependenciesMeta:
      react:
        optional: true
      react-dom:
        optional: true
  '@storybook/blocks@*':
    dependencies:
      react-dom: ^17.0.0
  '@storybook/core-client@*':
    peerDependenciesMeta:
      react:
        optional: true
      react-dom:
        optional: true
  '@storybook/core-common@*':
    peerDependenciesMeta:
      react:
        optional: true
      react-dom:
        optional: true
      webpack:
        optional: true
  '@storybook/mdx1-csf@*':
    dependencies:
      '@babel/core': ^7.0.0
      react: ^17.0.0
  '@storybook/router@*':
    peerDependenciesMeta:
      react:
        optional: true
      react-dom:
        optional: true
  '@storybook/store@*':
    peerDependenciesMeta:
      react:
        optional: true
      react-dom:
        optional: true
  '@storybook/react-webpack5@*':
    dependencies:
      webpack: ^5.0.0
    peerDependenciesMeta:
      'jest-specific-snapshot':
        optional: true
      'require-from-string':
        optional: true
  'graphql-config@*':
    dependencies:
      '@types/node': '*'
      'typescript': '*'
