enableTelemetry: false

nodeLinker: node-modules

npmScopes:
  fortawesome:
    npmRegistryServer: 'https://npm.fontawesome.com'

packageExtensions:
  '@graphql-codegen/cli@*':
    dependencies:
      '@types/node': '*'
      'typescript': '*'
  '@graphql-tools/graphql-tag-pluck@*':
    peerDependenciesMeta:
      '@babel/core':
        optional: true
  '@storybook/react-webpack5@*':
    peerDependenciesMeta:
      webpack:
        optional: true
