enableGlobalCache: false
enableTelemetry: false

nodeLinker: node-modules

npmScopes:
  fortawesome:
    npmRegistryServer: 'https://npm.fontawesome.com'
packageExtensions:
  '@endemolshinegroup/cosmiconfig-typescript-loader@*':
    peerDependenciesMeta:
      typescript:
        optional: true
  '@storybook/addon-docs@*':
    dependencies:
      '@babel/core': '^7.0.0'
      'webpack': '^5.0.0'
  '@storybook/core-common@*':
    peerDependenciesMeta:
      react:
        optional: true
      react-dom:
        optional: true
  '@storybook/mdx1-csf@*':
    dependencies:
      '@babel/core': '^7.0.0'
  '@storybook/router@*':
    peerDependenciesMeta:
      react:
        optional: true
      react-dom:
        optional: true
  '@storybook/store@*':
    peerDependenciesMeta:
      react:
        optional: true
      react-dom:
        optional: true
  'babel-plugin-transform-dynamic-import@*':
    dependencies:
      '@babel/core': '^7.0.0'

yarnPath: .yarn/releases/yarn-3.2.1.cjs
