version: 2.1

executors:
  general:
    docker:
      - image: cimg/base:2022.01
    resource_class: small

  backend:
    working_directory: ~/joinswoop/swoop
    docker:
      - image: swoopcircleci/ruby:3.0.2-buster-node-browsers-13.14.0
      - image: circleci/postgres:12.4-postgis-ram
      - image: circleci/redis:4.0.14
    resource_class: small

  nodejs:
    shell: /bin/bash --login
    working_directory: ~/joinswoop/swoop
    docker:
      - image: cimg/node:18.17.0@sha256:f7b0fe6a1735000db6ef20c7b715defb8108ab93ae0823dc4dd6fa8bc7801272
    resource_class: small

  fullstack:
    shell: /bin/bash --login
    working_directory: ~/joinswoop/swoop
    docker:
      - image: swoopcircleci/ruby:3.0.2-buster-node-browsers-13.14.0
      - image: circleci/postgres:12.4-postgis-ram
      - image: circleci/redis:4.0.14
      - image: elasticsearch:7.10.1

orbs:
  jq: circleci/jq@2.2.0
  slack: circleci/slack@4.5.3
  aws-s3: circleci/aws-s3@3.0.0
  aws-cli: circleci/aws-cli@2.0.6

jobs:
  seeds_rubocop_zeitwerk:
    executor: backend
    resource_class: medium
    steps:
      - checkout

  webpack_development:
    executor: nodejs
    resource_class: medium
    steps:
      - checkout

  webpack_production:
    executor: nodejs
    resource_class: medium
    steps:
      - checkout

  relay:
    executor: nodejs
    resource_class: medium
    steps:
      - checkout

  graphql-codegen:
    executor: nodejs
    steps:
      - checkout

  typescript:
    executor: nodejs

  stylelint:
    executor: nodejs
    steps:
      - checkout

  eslint:
    executor: nodejs
    steps:
      - checkout

  jest:
    executor: nodejs
    resource_class: 2xlarge
    steps:
      - checkout

  storybook:
    working_directory: ~/joinswoop/swoop
    shell: /bin/bash --login
    resource_class: large
    docker:
      - image: cimg/node:18.17.0-browsers@sha256:2274110c65f19f93f757655d93b7c8e8ec41de530fc2f11abc61be012f36117a
    steps:
      - checkout

  storybook-percy:
    working_directory: ~/joinswoop/swoop
    shell: /bin/bash --login
    resource_class: large
    docker:
      - image: swoopcircleci/ruby:3.0.2-buster-node-browsers-13.14.0
    steps:
      - checkout

  rspec:
    executor: backend
    steps:
      - checkout

  rspec_system:
    executor: fullstack
    steps:
      - checkout

workflows:
  version: 2
  codeclimate:
    jobs:
      - checkout_code_with_node
      - setup_code_climate_test_reporter
      - rspec
      - rspec_system
      - jest

  frontend:
    jobs:
      - graphql-codegen
      - relay
      - stylelint
      - eslint
      - typescript

  backend:
    jobs:
      - seeds_rubocop_zeitwerk

  webpack:
    jobs:
      - checkout_code_with_node
      - webpack_development
      - webpack_production
