name: yarn

on: push

jobs:
  yarn:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0

      - uses: actions/setup-node@969bd2663942d722d85b6a8626225850c2f7be4b # tag=v3.5.0
        with:
          cache: 'yarn'
          node-version-file: '.nvmrc'

      - run: corepack enable

      - name: Add Authentication for Private Packages
        run: yarn config set npmScopes.fortawesome.npmAuthToken ${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}

      - run: yarn install --immutable
