name: yarn

on: push

jobs:
  yarn:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3.8.1
        with:
          cache: 'yarn'
          node-version-file: '.nvmrc'

      - run: corepack enable

      - run: yarn install --immutable
