name: yarn

on: push

jobs:
  yarn:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0

      - uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # tag=v3.5.1
        with:
          cache: 'yarn'
          node-version-file: '.nvmrc'

      - run: corepack enable

      - name: Add Authentication for Private Packages
        run: yarn config set npmScopes.fortawesome.npmAuthToken ${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}

      - run: yarn install --immutable
