name: yarn

on: push

jobs:
  yarn:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Validate yarn Packages
        run: yarn install --immutable --immutable-cache --check-cache
