name: yarn

on: push

jobs:
  yarn:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0

      - uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3.8.1
        with:
          cache: 'yarn'
          node-version-file: '.nvmrc'

      - run: corepack enable

      - run: yarn install --immutable
