name: yarn

on: push

jobs:
  yarn:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0

      - uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
        with:
          cache: 'yarn'
          node-version-file: '.nvmrc'

      - run: corepack enable

      - name: Add Authentication for Private Packages
        run: yarn config set npmScopes.fortawesome.npmAuthToken ${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}

      - run: yarn install --immutable
