name: yarn

on: push

jobs:
  yarn:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3.0.2

      - uses: actions/setup-node@969bd2663942d722d85b6a8626225850c2f7be4b # tag=v3.5.0
        with:
          cache: 'yarn'
          node-version-file: '.nvmrc'

      - run: corepack enable

      - name: Add Authentication for Private Packages
        run: yarn config set npmScopes.fortawesome.npmAuthToken ${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}

      - run: yarn install --immutable
